const DEFAULT_BASE_URL = 'http://127.0.0.1:4173';

const REQUEST_IDS = {
  call: 'R-2026-001',
  secondTm: 'R-2026-006',
  sales: 'R-2026-005',
  claims: 'R-2026-010',
  staff: 'U-STF-03',
};

const CAPTURE_TARGETS = [
  {
    slug: 'dashboard',
    title: '데이터 건전성 대시보드',
    group: '공통',
    tab: 'dashboard',
    role: 'admin',
    note: '관리자 기준 전체 현황 화면',
  },
  {
    slug: 'customers',
    title: '고객 관리',
    group: '공통',
    tab: 'customers',
    role: 'admin',
    note: '고객 목록과 상세 진입의 시작점',
  },
  {
    slug: 'requests',
    title: '처리 현황',
    group: '공통',
    tab: 'requests',
    role: 'call_lead',
    note: '접수 건의 전체 진행 단계 확인 화면',
  },
  {
    slug: 'case-detail-call',
    title: '케이스 상세 [콜팀]',
    group: '공통',
    tab: 'case-detail',
    role: 'call_lead',
    requestId: REQUEST_IDS.call,
    section: 'call',
    note: '콜팀 기준 케이스 상세',
  },
  {
    slug: 'case-detail-sales',
    title: '케이스 상세 [영업팀]',
    group: '공통',
    tab: 'case-detail',
    role: 'sales_lead',
    requestId: REQUEST_IDS.sales,
    section: 'sales',
    note: '영업팀 기준 케이스 상세',
  },
  {
    slug: 'case-detail-claims',
    title: '케이스 상세 [청구팀]',
    group: '공통',
    tab: 'case-detail',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    section: 'claims',
    note: '청구팀 기준 케이스 상세',
  },
  {
    slug: 'leads',
    title: 'DB 배정 관리 (신청 유입)',
    group: '콜팀',
    tab: 'leads',
    role: 'call_lead',
    note: '팀장용 분류 및 배정 화면',
  },
  {
    slug: 'consultation',
    title: '상담 리스트 (전체)',
    group: '콜팀',
    tab: 'consultation',
    role: 'call_lead',
    requestId: REQUEST_IDS.call,
    note: '상담 목록 및 작업 진입 화면',
  },
  {
    slug: 'tm-first',
    title: '1차 TM (S5)',
    group: '콜팀',
    tab: 'tm-first',
    role: 'call_lead',
    requestId: REQUEST_IDS.call,
    note: '1차 TM 전용 화면',
  },
  {
    slug: 'tm-second',
    title: '2차 TM (S6)',
    group: '콜팀',
    tab: 'tm-second',
    role: 'call_lead',
    requestId: REQUEST_IDS.secondTm,
    note: '2차 TM 전용 화면',
  },
  {
    slug: 'tm-checklist',
    title: 'TM 체크리스트',
    group: '콜팀',
    tab: 'tm-checklist',
    role: 'call_lead',
    requestId: REQUEST_IDS.secondTm,
    note: 'TM 체크리스트 전용 화면',
  },
  {
    slug: 'handoff',
    title: '이관(Handoff) 관리',
    group: '영업팀',
    tab: 'handoff',
    role: 'sales_lead',
    note: '콜팀에서 영업팀으로 넘어오는 이관 관리',
  },
  {
    slug: 'meeting-schedule',
    title: '미팅 스케줄 관리',
    group: '영업팀',
    tab: 'meeting-schedule',
    role: 'sales_lead',
    note: '미팅 일정 배정 및 관리 화면',
  },
  {
    slug: 'meeting-all',
    title: '미팅 리스트 (전체)',
    group: '영업팀',
    tab: 'meeting-all',
    role: 'sales_lead',
    requestId: REQUEST_IDS.sales,
    note: '미팅 전체 큐',
  },
  {
    slug: 'meeting-pre-analysis',
    title: '사전 분석 (S7)',
    group: '영업팀',
    tab: 'meeting-pre-analysis',
    role: 'sales_lead',
    requestId: REQUEST_IDS.sales,
    note: '미팅 전 사전 분석 화면',
  },
  {
    slug: 'meeting-on-site',
    title: '미팅 실행 (S8)',
    group: '영업팀',
    tab: 'meeting-on-site',
    role: 'sales_lead',
    requestId: REQUEST_IDS.sales,
    note: '현장 미팅 실행 화면',
  },
  {
    slug: 'meeting-contract-close',
    title: '계약 체결 (S9)',
    group: '영업팀',
    tab: 'meeting-contract-close',
    role: 'sales_lead',
    requestId: REQUEST_IDS.sales,
    note: '계약 체결 및 후속 처리',
  },
  {
    slug: 'contracts',
    title: '계약 체결 및 관리',
    group: '영업팀',
    tab: 'contracts',
    role: 'sales_lead',
    note: '계약 목록 화면',
  },
  {
    slug: 'claims-all',
    title: '청구 리스트 (전체)',
    group: '청구팀',
    tab: 'claims-all',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '청구팀 전체 큐',
  },
  {
    slug: 'claims-receipt',
    title: '청구 접수 (S10)',
    group: '청구팀',
    tab: 'claims-receipt',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '청구 접수 단계 전용 화면',
  },
  {
    slug: 'claims-unpaid',
    title: '미지급금 분석 (S11)',
    group: '청구팀',
    tab: 'claims-unpaid',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '미지급금 분석 단계 전용 화면',
  },
  {
    slug: 'claims-doc-issuance',
    title: '서류 발급 (S12)',
    group: '청구팀',
    tab: 'claims-doc-issuance',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '서류 발급 단계 전용 화면',
  },
  {
    slug: 'claims-final',
    title: '최종 분석 (S13)',
    group: '청구팀',
    tab: 'claims-final',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '최종 분석 단계 전용 화면',
  },
  {
    slug: 'claims-issuance',
    title: '서류 발급 대행 - 전체 리스트 [claims alias]',
    group: '청구팀',
    tab: 'claims-issuance',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '청구 단계에서 접근하는 발급 대행 별칭 화면',
  },
  {
    slug: 'issuance-master',
    title: '서류 발급 대행 - 전체 리스트',
    group: '청구팀',
    tab: 'issuance-master',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '발급 대행 마스터 화면',
  },
  {
    slug: 'issuance-manager',
    title: '서류 발급 대행 - 전체 리스트 [manager alias]',
    group: '청구팀',
    tab: 'issuance-manager',
    role: 'claims_lead',
    requestId: REQUEST_IDS.claims,
    note: '매니저 별칭 탭',
  },
  {
    slug: 'issuance-staff',
    title: '서류 발급 대행 - 직원별 리스트',
    group: '청구팀',
    tab: 'issuance-staff',
    role: 'claims_lead',
    requestId: REQUEST_IDS.staff,
    note: '직원별 작업 화면',
  },
  {
    slug: 'payment-confirm',
    title: '지급 확인 (S14)',
    group: '후속 처리',
    tab: 'payment-confirm',
    role: 'claims_lead',
    note: '지급 확인 화면',
  },
  {
    slug: 'aftercare',
    title: '사후 관리 (S15)',
    group: '후속 처리',
    tab: 'aftercare',
    role: 'admin',
    note: '지급 이후 관리 화면',
  },
  {
    slug: 'referral-management',
    title: '소개 / Growth Loop (S16-S17)',
    group: '후속 처리',
    tab: 'referral-management',
    role: 'admin',
    note: '소개 및 성장 루프 화면',
  },
  {
    slug: 'simple-claims',
    title: '간편청구 워크플로우 (Q1-Q9)',
    group: '후속 처리',
    tab: 'simple-claims',
    role: 'claims_lead',
    note: '간편청구 전용 워크플로우',
  },
  {
    slug: 'voc',
    title: 'CS / VOC 관리',
    group: '운영 지원',
    tab: 'voc',
    role: 'cs',
    note: 'VOC 및 CS 대응 화면',
  },
  {
    slug: 'compliance',
    title: '준법 / 개인정보 대시보드',
    group: '운영 지원',
    tab: 'compliance',
    role: 'compliance',
    note: '준법 및 개인정보 대시보드',
  },
  {
    slug: 'admin-operations',
    title: '관리업무 운영',
    group: '운영 지원',
    tab: 'admin-operations',
    role: 'admin',
    note: '관리업무 운영 화면',
  },
  {
    slug: 'dropoff',
    title: '이탈 사유 분석 (Read-only)',
    group: '운영 지원',
    tab: 'dropoff',
    role: 'cs',
    note: '이탈 로그 및 사유 분석',
  },
  {
    slug: 'daily-report',
    title: '일일 보고서',
    group: '운영 지원',
    tab: 'daily-report',
    role: 'call_lead',
    note: '일일 리포트 작성 및 확인',
  },
  {
    slug: 'documents',
    title: '서류 및 동의서 관리',
    group: '운영 지원',
    tab: 'documents',
    role: 'admin',
    note: '문서 허브 기본 화면',
  },
  {
    slug: 'settings',
    title: '시스템 설정',
    group: '운영 지원',
    tab: 'settings',
    role: 'admin',
    note: '시스템 설정 화면',
  },
];

const UNMOUNTED_PAGE_FILES = [
  'src/app/pages/CustomerDetail.tsx',
  'src/app/pages/IssuanceManager.tsx',
  'src/app/pages/IssuanceOperations.tsx',
  'src/app/pages/LeadManagement.tsx',
  'src/app/pages/Qualification.tsx',
];

module.exports = {
  CAPTURE_TARGETS,
  DEFAULT_BASE_URL,
  REQUEST_IDS,
  UNMOUNTED_PAGE_FILES,
};
